### PR TITLE
Fix: Convert to React / ES6 (fixes #10)

### LINKED ISSUE #6: move u-display-none to "navigation-logo"
adapt-navigationLogo v2.1.0

Currently when `"_hideLogoForMobile": true`, `u-display-none` is applied to `img.navigation-logo__image`. This leaves in place the parent divs and their styling. Such remnants interfere with the goal of removing the logo and recapturing space in the navbar.

I suggest that `u-display-none` be added to `navigation-logo` instead of `img.navigation-logo__image`.
\------------------

In this first screenshot, I added a white border to `navigation-logo` to highlight what remains behind. These remnant divs push out of alignment the text "View Progress".
nav-logo-1

In this second screenshot, the white border remains in code but is not visible because I moved `u-display-none` to the parent  `navigation-logo`. Consequently, "View Progress" falls in-line.
image

### LINKED ISSUE #8: Add data-order support for sorting navigation
Allowed the sorting of navigation elements according to a data-order attribute in the dom
https://github.com/adaptlearning/adapt-contrib-core/pull/61

### LINKED ISSUE #9: Add support for authoring tool 1

### LINKED ISSUE #10: Convert to React / ES6

### PR DESCRIPTION
**Pull request by swashbuck**
Fixes #10 
Fixes #6 
Fixes #8 
Fixes #9 

### Changes

- #10 Uses JSX template
- #10 Updates JS code to ES6
- #6 When _hideLogoForMobile is true, this now makes navigation-logo hidden instead of the image.
- #8 Add data-order support for sorting navigation
- #9 Update schemas

### CODE REVIEW

**Comment by swashbuck** [comment]
@chris-steele I'm looking for advice on this PR.

I need to be able to change the mobile image src (and optionally hide the image) when the device changes.  This currently works.  However, I was under the impression that modifying the model values would automatically rerender the component?  Instead, I have to call render() in both initialize() and onDeviceResize() in the view.  Is this because I'm using ReactDOM.render and that requires a manual rerender as needed?

Would it be better to move the resizing logic to the JSX and use state / useEffect to make the updates?

**Comment by chris-steele** [comment]
Hey @swashbuck, if you look at `AdaptView` you can see that `ReactDOM.render` is called in response to `device:changed` (via the `changed` method). This takes care of React components being responsive. To respond to model changes `AdaptView` sets an `all` listener which in turn invokes a render. You could do similar with `NavigationLogoView`. N.B. I do not recommend setting listeners on child/descendant models as happens in `AdaptView`. This is a hack for Adapt, but it is something of a React anti-pattern. In React things are top down. A parent rendering causes its children to render, not the other way around.

**Review by chris-steele — APPROVED** [review]
`AdaptView` typically expects an `AdaptModel` (or subclass), but it's not a hard dependency these days so this should work just fine.

**Comment by swashbuck** [comment]
Needs schema update to complete #8

**Review by chris-steele — CHANGES_REQUESTED** [review]
Nice to see another plugin moving forward into React and ES6! Would you mind having a look at [my review](https://github.com/cgkineo/adapt-navigationTitle/pull/9#pullrequestreview-1234411293) of your PR for `navigationTitle` and consider similar changes here?

**Review by chris-steele — APPROVED** [review]

File: templates/navigationLogo.jsx [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+
+    <div
+      className={classes([
+        'navigation-logo__inner',
+        _fillNavHeight && 'is-fill'
+      ])}
+    >
+      <img
+        className='navigation-logo__image'
+        src={src}
```
[the remark this answers is not in the document]
Comment (swashbuck) [reply templates/navigationLogo.jsx:21]: Thanks, @kirsty-hames .  This should be fixed now.  The problem was happening when _mobileSrc was empty.

I will look into the AT issues.  Thanks for spotting.

File: bower.json [hunk 2]
```diff
@@ -1,8 +1,9 @@
 {
   "name": "adapt-navigationLogo",
   "version": "2.1.0",
-  "framework": ">=5",
+  "framework": ">=5.20.0",
```
Comment (guywillis) [inline bower.json:4]: With the removal of `.u-float-left` from the less this should be bumped to 5.24.4

File: README.md [hunk 3]
```diff
@@ -35,6 +35,7 @@ No known limitations
 **Version number:**  2.1.0
```
Comment (guywillis) [inline README.md:35]: Could we change the double spacing at the end of the version number and subsequent lines to a html
tag instead to avoid the line breaks being removed when white space is removed.

**Review by guywillis — APPROVED** [review]
👍

**Comment by swashbuck** [comment]
Schemas updated and ready for a full review.
